config/routes.rb
Rails.application.routes.draw do
  root to: "application#index"
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create", as: "session"
  delete '/sessions', to: "sessions#destroy", as: "logout"
  get '/search', to: "tiers#search", as: "search"
  resources :customers
  resources :customers do
    resources :cakes, only: [:index, :new]
  end
  resources :cakes, only: [:create, :edit, :show, :destroy]
  resources :cakes do
    resources :tiers, only: [:new, :index]

  end
  resources :tiers, only: [:create, :show, :edit, :update, :destroy]
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cake.rb
class Cake < ApplicationRecord
    has_many :tiers, dependent: :destroy
    has_many :customers, through: :tiers
    accepts_nested_attributes_for :tiers
   

    scope :recent_create, -> { order('created_at DESC') }
    scope :recent_use, -> { order('updated_at DESC') }
   
    scope :search, -> (params) {where("lower(flavor) LIKE ?", "%#{params}%")}
   
    

end

app/models/customer.rb
class Customer < ApplicationRecord
    validates :username, presence: true
    validates :username, uniqueness: true
    validates :email, presence: true
    validates :email, uniqueness: true
    validates :password, presence: true
    has_secure_password
    has_many :tiers
    has_many :cakes, through: :tiers
    def self.from_omniauth(auth)
       where(email: auth.info.email).first_or_initialize do |customer|
          customer.username = auth.info.name
          customer.email = auth.info.email
          customer.password = SecureRandom.hex
        end
    end
end

app/models/tier.rb
class Tier < ApplicationRecord
    belongs_to :cake
    belongs_to :customer
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?, :current_customer, :authorized, :username

    def index
      if logged_in?
        redirect_to customer_path(current_customer)
      else 
        render '/homepage'
     end
    end 
  
    def current_customer
      if session[:customer_id]
      current_customer = Customer.find(session[:customer_id])
         
      end
    end 
              
    def logged_in?
      !!current_customer
    end 
      
    def authorize
      if !logged_in?
        redirect_to login_path
      end 
    end 
      
    def authenticate 
      if !current_customer
        redirect_to current_customer
      end 
    end 
end

app/controllers/cakes_controller.rb
class CakesController < ApplicationController
    before_action :set_cake, only: [:show, :edit, :update]


    def index
        cake_id = Cake.find_by(params[:id])
        tier_id = Tier.find_by(params[:id])
        @cakes = current_customer.cakes.recent_create
        if params[:q] && !params[:q].empty?
            @cakes = @cakes.search(params[:q].downcase)
        end
    end
    
    def new
        @cake = Cake.new
    end

    def create
        @cake = Cake.create(cake_params)
        if @cake.save
               
         redirect_to new_cake_tier_path(@cake)
        else 
            flash[:alert] = "Your cake was not saved"
         render :new
        end
      end

    def show
        @cake = Cake.find(params[:id])
        @tier = Tier.find(params[:id])
    end
     
    def edit
       @cake = Cake.find_by(id: params[:id])
    end
 
    def update            
        @cake = Cake.find(params[:id])
          if @cake.update(cake_params) 
            redirect_to edit_tier_path(@cake)
            else
            flash[:alert] = "Your cake was not updated"
            render edit_cake_path(@cake)
          end
    end

    def destroy
        Cake.find(params[:id]).destroy
         redirect_to customer_cakes_path(customer_id: [current_customer.id])
    end

        private
    def set_cake
        @cake = Cake.find(params[:id])
    end

    def cake_params
        params.require(:cake).permit(:style, tiers_attributes: [:flavor, :filling, :frosting, :size, :shape, :instructions, :cake_id, :customer_id])
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update]

    

  def new
    @customer = Customer.new        
  end

  def create
        @customer = Customer.create(customer_params)
        if @customer.save
          params[:customer][:password]
          session[:customer_id] = @customer.id
          redirect_to customer_path(@customer)
        else
          if Customer.find_by(username: params[:customer][:username]) || Customer.find(email: params[:customer][:email])
            flash[:alert] = "Looks like you've already signed up!"
            redirect_to login_path
          else 
            render :new
          end 
        end 
      end
      

      def show 
            
      end
      def edit

      end

      def update
        authenticate 
        @customer.update(customer_params)
          if @customer.save
            redirect_to customer_path(@customer)
          else 
            flash[:notice] = "Your account was not updated. Please check your username & password."     
            render :edit
          end 
      end

    
    private
    def customer_params
        params.require(:customer).permit(:username, :email, :password)
      end  
    
    def set_customer
        @customer = Customer.find(params[:id])
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end 
  
    def create
      if customer = Customer.find_by(username: params[:username])
        if customer && customer.authenticate(params[:password])
          session[:customer_id] = customer.id
          
          redirect_to customer_path(customer) 
        end 
      else  
        flash[:alert] = "Please try again or Sign Up."
        redirect_to login_path
      end
    end

    def omniauth
      @customer = Customer.from_omniauth(auth)
      @customer.save
      session[:customer_id] = @customer.id
      redirect_to root_path
    end

    def destroy
        session[:customer_id] = nil 
        redirect_to login_path 
    end 
    
  private
    def auth
      request.env['omniauth.auth']
    end
end

app/controllers/tiers_controller.rb
class TiersController < ApplicationController
      before_action :set_customer
    
    
    def index
        @cake = Cake.find_by(id: params[:cake_id])
        @tier = Tier.find_by(id: params[:id])
    end
    def search
        binding.pry
        @tiers = current_customer.tiers.search
    end


    def new 
       @cake = Cake.find(params[:cake_id]) 
        @tier = Tier.new
        @tier.cake = @cake
    end
    
    def create
      @tier = current_customer.tiers.build(tier_params)
        if @tier.save 
        @cake = @tier.cake       
        redirect_to tier_path(@tier)
        else
            flash[:alert] = "Your tiers were not created"
            render 'new'
        end
    end

    def show
        @tier = Tier.find(params[:id])
    end
   
    def edit
        @cake = Cake.find_by(id: params[:id])
         @tier = Tier.find_by(id: params[:id])
    end

    def update
        @tier = Tier.find(params[:id])
              
         if @tier.update(tier_params)
            redirect_to tier_path(@tier)

         else
            flash[:alert] = "Your cake was not updated"
            render edit_tier_path(@tier)
         end
    end
    def destroy
        @tier.destroy
        redirect_to customer_cakes_path(customer_id: [current_customer.id])
    end


    private

    def tier_params
       
        params.require(:tier).permit(:flavor, :filling, :frosting, :size, :shape, :instructions, :cake_id)
    end
    # def set_cake
    #     @cake = Cake.find(params[:cake_id])
    # end
    
    def set_customer
        @customer = Customer.find(current_customer.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cakes/_cakeform.html.erb
<%= form_for @cake do |f| %>
    <%= f.label "Style of Cake: " %><br>
    <br><%= f.collection_select(:style, Cake.all, :style, :style) %><br>      
    <%= f.submit "Update Cake Style" %>
    <% end %>
    <%= link_to "View my cakes", customer_cakes_path(current_customer) %><br>
    <%= render 'shared/links' %>
    
    

app/views/cakes/_cakes.html.erb
<h2><%= "#{current_customer.username} Select the cake you would like to view" %></h2>
<% @cakes.each do | cake | %>
 <h3> Cake Style: <%= cake.style %></h3><br>

    <% cake.tiers.each do | tier | %>

     <cakes>Tier Flavor: <%= tier.flavor %><br>
      Tier Filling: <%= tier.filling %><br>
      Tier Frosting:<%= tier.frosting %><br>
      Tier Size: <%= tier.size %> inches<br>
      Tier Shape: <%= tier.shape %><br>
      Instructions for tier: <%= tier.instructions %><br></cakes>
     <% end %>
    
     <br><%= link_to "Edit this cake", edit_cake_path(cake) %>
     <%= button_to "Delete This Cake", cake_path(cake), method: :delete %>
     <% end %>
     <%= render 'shared/links' %>
      <%= link_to "Create a new cake", new_customer_cake_path(current_customer) %><br>
     

app/views/cakes/edit.html.erb
<% if @cake.errors.any? %>
    <ul id="errors">
    <% @cake.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>
<h1> Edit your Cake Style </h1>

<%= render 'cakeform' %>

        

app/views/cakes/index.html.erb
<%= render 'shared/links' %>


<%= form_tag("/cakes", method: "get") do %>
<%= label_tag(:q, "Search by flavor:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>

<% end %>

 <% if @cakes.empty? %>
   <h2> You have no cakes yet. Please make a cake 
   <%= link_to "Create a new cake", new_customer_cake_path(current_customer) %></h2><br>
   <% else %>
   <%= render partial: "cakes", locals: {cakes: @cakes} %>

   <% end %>



     

app/views/cakes/new.html.erb
<% if @cake.errors.any? %>
    <ul id="errors">
    <% @cake.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>


<h1> Design A New Cake</h1>
<h2>Please select the style of cake you would like to make.</h2>
<%= render 'cakeform' %>

app/views/cakes/search.html.erb
<h2><%= "#{current_customer.username} Search for the style of cake you would like to see" %></h2>
<% @cakes.each do | cake | %>
 <h3> Cake Style: <%= cake.style %></h3><br>

    <% cake.tiers.each do | tier | %>

      Tier Flavor: <%= tier.flavor %><br>
      Tier Filling: <%= tier.filling %><br>
      Tier Frosting:<%= tier.frosting %><br>
      Tier Size: <%= tier.size %> inches<br>
      Tier Shape: <%= tier.shape %><br>
      Instructions for tier: <%= tier.instructions %><br>
     <% end %>
    
     <br><%= link_to "Edit this cake", edit_cake_path(cake) %>
     <%= button_to "Delete This Cake", cake_path(cake), method: :delete %>
     <% end %>
     <%= render 'shared/links' %>
      <%= link_to "Create a new cake", new_customer_cake_path(current_customer) %><br>

app/views/cakes/show.html.erb
<h3>Here is your cake:</h3>
<br>

Cake Style: <%= @cake.style %><br>
<% @cake.tiers.each do | tier | %>
   <cakes> Tier Flavor: <%= tier.flavor %><br>
      Tier Filling: <%= tier.filling %><br>
      Tier Frosting:<%= tier.frosting %><br>
      Tier Size: <%= tier.size %> inches<br>
      Tier Shape: <%= tier.shape %><br>
      Instructions for tier: <%= tier.instructions %><br></cakes>

     <%= link_to "Edit this cake", edit_cake_path(@cake) %>
     <submits><%= button_to "Delete This Cake", cake_path(cake), method: :delete %></submits>

     <% end %>
     <%= render 'shared/links' %>
     <%= render 'shared/web_links' %>

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %><br><br>
    <%= f.label :email %>
    <%= f.email_field :email %><br><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br><br>
    <%= f.submit %><br>
    
    <%= link_to "Log In", login_path %><br>
    <%= link_to "Log In with Google", '/auth/google_oauth2' %>
  <% end %>
   

app/views/customers/edit.html.erb
<header>
  <h1>Edit Customer Account</h1>
</header>

<%= render 'form'%>

app/views/customers/new.html.erb
<header>
  <h1>Make a Customer Account!</h1> 
</header>

<div>
<% if @customer.errors.any? %>
    <ul>
    <% @customer.errors.full_messages.each do |msg| %>
      <li id="flash"><%= msg %></li>
    <% end %>
    </ul>
<% end %>
<%= render 'form' %>
</div>

app/views/customers/show.html.erb
<% if @customer.errors.any? %>
    <ul>
    <% @customer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>


<h2><%= "#{current_customer.username}, would you like to create a cake or view all cakes?" %></h2>
<%= render 'shared/web_links' %>
<%= render 'shared/links' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zsa Zsa's CakeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style.css' %>
  </head>
  <center><h1>Zsa Zsa's Cake Shop</h1><br>
  <h2>Eat More Cake </h2><center>
    <h3>Live Happy</h3>
     <%= yield %>
  <body>
  <h2><% flash.each do |type, msg| %>
      <div id="flash">
        <%= msg %>
      </div></h2>
    <% end %>
  </body>
</html>

app/views/shared/_links.html.erb
<div>
<%= link_to "Logout", logout_path, method: :delete %>
</div>

app/views/shared/_web_links.html.erb
<div>
<%= link_to "View my cakes", customer_cakes_path(current_customer) %><br>
<%= link_to "Create a new cake", new_customer_cake_path(current_customer) %><br>
<%= link_to "Edit Customer Account", edit_customer_path(current_customer) %>

</div>

app/views/tiers/_tiers_form.html.erb
  
     <%= form_with(model: @tier, url: tiers_path) do | f | %>
           
      <tiers><%= f.label "Tier Flavor" %>
        <%= f.select(:flavor, ['Chocolate', 'Vanilla', 'Strawberry', 'Maple']) %><br>
        <%= f.label "Frosting" %> 
        <%= f.select(:frosting, ['Chocolate', 'Vanilla', 'Cream Cheese', 'Maple']) %><br>
        <%= f.label "Filling" %>
        <%= f.select(:filling, ['Chocolate', 'Vanilla Cream', 'Cream Cheese', 'Maple', 'Cookies n Cream', 'Strawberries & Cream']) %><br>
        <%= f.label "Tier size in inches"%>
        <%= f.number_field :size, in: 4...21, step: 2 %><br>
        <%= f.label "Shape of tier" %>
        <%= f.select(:shape, ['Square', 'Round', 'Oval', 'Ball']) %>
        <%= f.label "Instructions" %>
        <%= f.text_area :instructions %>
        <%= f.hidden_field :cake_id %></tiers>       
        
        <submits><%= f.submit "Create Cake", data:{ disable_with: false } %></submits>
        <% end %>
        <%= render 'shared/links' %>
        <%= render 'shared/web_links' %>

        
    
     

app/views/tiers/edit.html.erb
<h2>Edit the tiers for your cake</h2><br>
<h3>Cake Style: <%= @cake.style %><br></h3><br>
<%= form_with(model: @tier) do | f | %>
              
        <%= f.label "Tier Flavor: " %>
        <%= f.select(:flavor, ['Chocolate', 'Vanilla', 'Strawberry', 'Maple']) %><br>
        <%= f.label "Frosting: " %> 
        <%= f.select(:frosting, ['Chocolate', 'Vanilla', 'Cream Cheese', 'Maple']) %><br>
        <%= f.label "Filling: " %>
        <%= f.select(:filling, ['Chocolate', 'Vanilla Cream', 'Cream Cheese', 'Maple', 'Cookies n Cream', 'Strawberries & Cream']) %><br>
        <%= f.label "Tier size in inches: "%>
        <%= f.number_field :size, in: 4...21, step: 2 %><br >
        <%= f.label "Shape of tier: " %>
        <%= f.select(:shape, ['Square', 'Round', 'Oval', 'Ball']) %>
        <%= f.label "Instructions: " %>
        <%= f.text_area :instructions %>
        <%= f.hidden_field :cake_id %>       
        
        <%= f.submit %>
        <% end %>
        <%= render 'shared/links' %>
        <%= render 'shared/web_links' %>

        
    
     

app/views/tiers/index.html.erb
<h4>Here is your saved cake!!</h4>
<h3>Cake Style: <%= @cake.style %><br>
<% @cake.tiers.each do | tier | %>
    Tier Flavor:  <%= tier.flavor %><br>
      Tier Filling:  <%= tier.filling %><br>
      Tier Frosting:  <%= tier.frosting %><br>
      Tier Size:  <%= tier.size %> inches<br>
      Tier Shape:  <%= tier.shape %><br>
      Instructions for tier:  <%= tier.instructions %><br></h3>
     <% end %>
     <%= link_to "Edit this cake", edit_cake_path(@cake) %>
     <%= render 'shared/links' %>
     <%= render 'shared/web_links' %>
    

app/views/tiers/new.html.erb
<% if @tier.errors.any? %>
    <ul id="errors">
    <% @tier.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>


<h3>Create The Tiers for your cake<br>
Cake Style: <%= @cake.style %><br></h3>
<%= render 'tiers_form' %>

app/views/tiers/show.html.erb
<h3>Here is your cake. If you are satisfied with it, save it!!</h3>
<h3>Cake Style: <%= @tier.cake.style %></h3>
<h4>Tiers in this cake</h4>   


      <br>Tier Flavor: <%= @tier.flavor %><br>
      Tier Filling: <%= @tier.filling %><br>
      <br>Tier Frosting: <%= @tier.frosting %><br>
      <br>Tier Size: <%= @tier.size %> inches<br> 
      <br>Tier Shape: <%= @tier.shape%><br>
      <br>Tier Instructions: <%= @tier.instructions %><br>
      <br><%= hidden_field_tag :cake_id %>
      

<%= link_to "Save this cake", cake_tiers_path(@tier.cake) %><br>
<%= link_to "Edit this cake", edit_cake_path(@tier.cake) %><br>
<%= button_to "Delete This Cake", cake_path(@tier.cake), method: :delete %>